from easydict import EasyDict as edict


__C = edict()
model_cfg = __C
__C.GARMAGE_JIGSAW = edict()


# encoders (feature extractors)
__C.GARMAGE_JIGSAW.USE_POINT_FEATURE = True
__C.GARMAGE_JIGSAW.USE_LOCAL_POINT_FEATURE = True
__C.GARMAGE_JIGSAW.USE_GLOBAL_POINT_FEATURE = False
__C.GARMAGE_JIGSAW.USE_UV_FEATURE = False
__C.GARMAGE_JIGSAW.USE_LOCAL_UV_FEATURE = False
__C.GARMAGE_JIGSAW.USE_GLOBAL_UV_FEATURE = False
__C.GARMAGE_JIGSAW.ENCODE_ALL_ONCE = False  #  Use the same encoder to extract all features
__C.GARMAGE_JIGSAW.PC_FEAT_DIM = 128
__C.GARMAGE_JIGSAW.UV_FEAT_DIM = 128
__C.GARMAGE_JIGSAW.AFF_FEAT_DIM = 512
__C.GARMAGE_JIGSAW.AFFINITY = 'aff_dual'
__C.GARMAGE_JIGSAW.ENCODER = 'pointnet2_pt.msg.dynamic'


# PointTransformer
__C.GARMAGE_JIGSAW.TF_LAYER_NUM = 1
__C.GARMAGE_JIGSAW.TF_NUM_HEADS = 8
__C.GARMAGE_JIGSAW.TF_NUM_SAMPLE = 16
# Whether to use PointTransformer Blocks to encapsulate each PointTransformer separately
__C.GARMAGE_JIGSAW.USE_TF_BLOCK = False
__C.GARMAGE_JIGSAW.TF = edict()
__C.GARMAGE_JIGSAW.TF.NORM = "batch"  # choice: "batch", "instance"


# feature conv before PointTransformer
__C.GARMAGE_JIGSAW.FEATURE_CONV = edict()
__C.GARMAGE_JIGSAW.FEATURE_CONV.USE_FEATURE_CONV = False
__C.GARMAGE_JIGSAW.FEATURE_CONV.TYPE = "default"
__C.GARMAGE_JIGSAW.FEATURE_CONV.LAYER_NUM = 1
__C.GARMAGE_JIGSAW.FEATURE_CONV.KERNEL_SIZE = 3
__C.GARMAGE_JIGSAW.FEATURE_CONV.DILATION = 1
# feature conv after PointTransformer
__C.GARMAGE_JIGSAW.FEATURE_CONV_2 = edict()
__C.GARMAGE_JIGSAW.FEATURE_CONV_2.USE_FEATURE_CONV = False
__C.GARMAGE_JIGSAW.FEATURE_CONV_2.TYPE = "default"
__C.GARMAGE_JIGSAW.FEATURE_CONV_2.LAYER_NUM = 1
__C.GARMAGE_JIGSAW.FEATURE_CONV_2.KERNEL_SIZE = 3
__C.GARMAGE_JIGSAW.FEATURE_CONV_2.DILATION = 1


# point classifier
__C.GARMAGE_JIGSAW.PC_CLS_THRESHOLD = 0.8
# stitch predictor
__C.GARMAGE_JIGSAW.SINKHORN_MAXITER = 20
__C.GARMAGE_JIGSAW.SINKHORN_TAU = 0.05


# loss
__C.GARMAGE_JIGSAW.LOSS = edict()
"""
value of MAT_LOSS_TYPE should be selected in ["local", "global"]
local : only calculate mat loss in stitch loss, witch may cause cls loss raise
global : calculate mat loss in all points
"""
__C.GARMAGE_JIGSAW.LOSS.MAT_LOSS_TYPE = "local"
__C.GARMAGE_JIGSAW.LOSS.MAT_LOSS_SYM = True
__C.GARMAGE_JIGSAW.LOSS.w_cls_loss = 0.5
__C.GARMAGE_JIGSAW.LOSS.w_mat_loss = 0.0


# params for two stage training
# point classifier
__C.GARMAGE_JIGSAW.POINTCLASSIFIER = edict()
__C.GARMAGE_JIGSAW.POINTCLASSIFIER.TF_LAYER_NUM = 1
__C.GARMAGE_JIGSAW.POINTCLASSIFIER.TF_NUM_HEADS = 8
__C.GARMAGE_JIGSAW.POINTCLASSIFIER.TF_NUM_SAMPLE = 16
__C.GARMAGE_JIGSAW.POINTCLASSIFIER.USE_TF_BLOCK = False
__C.GARMAGE_JIGSAW.POINTCLASSIFIER.NORM = "batch"  # choice: "batch" , "instance"
# stitch predictor
__C.GARMAGE_JIGSAW.STITCHPREDICTOR = edict()
__C.GARMAGE_JIGSAW.STITCHPREDICTOR.TF_LAYER_NUM = 1
__C.GARMAGE_JIGSAW.STITCHPREDICTOR.TF_NUM_HEADS = 8
__C.GARMAGE_JIGSAW.STITCHPREDICTOR.TF_NUM_SAMPLE = 16
__C.GARMAGE_JIGSAW.STITCHPREDICTOR.USE_TF_BLOCK = False
__C.GARMAGE_JIGSAW.STITCHPREDICTOR.NORM = "batch"  # choice: "batch" , "instance"


def get_model_cfg():
    return model_cfg.GARMAGE_JIGSAW